spring.application.name=backend
server.port=8080

# Clerk JWT Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_ISSUER_URI}/.well-known/jwks.json

# Rate Limit
app.rate-limit.requests-per-minute=${REQUEST_PER_MINUTE}

# CORS Configuration
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

# Clerk Webhook Configuration
clerk.webhook.secret=${CLERK_WEBHOOK_SECRET}

# Tigris Storage Configuration
tigris.endpoint=${TIGRIS_ENDPOINT}
tigris.region=${TIGRIS_REGION}
tigris.bucket-name=${TIGRIS_BUCKET_NAME}
tigris.access-key-id=${TIGRIS_ACCESS_KEY_ID}
tigris.secret-access-key=${TIGRIS_SECRET_ACCESS_KEY}

spring.profiles.active=local
